HB_TAG_MAX: switched from 2^32-1 (UINT_MAX) to 2^31-1 (INT_MAX)
An error occurs when building with clang — HB_TAG_MAX value doesn't fit into the `value` field of struct GEnumValue:
hb-gobject-enums.cc:289:11: error: constant expression evaluates to 4294967295 which cannot be narrowed to type 'gint' (aka 'int')
      [-Wc++11-narrowing]
        { _HB_SCRIPT_MAX_VALUE, "_HB_SCRIPT_MAX_VALUE", "-hb-script-max-value" },
          ^~~~~~~~~~~~~~~~~~~~
hb-gobject-enums.cc:289:11: note: override this message by inserting an explicit cast
        { _HB_SCRIPT_MAX_VALUE, "_HB_SCRIPT_MAX_VALUE", "-hb-script-max-value" },
          ^~~~~~~~~~~~~~~~~~~~
          static_cast<gint>(  )