[ci] don't use harfbuzz.cc with -Weverything
Causes

In file included from src/harfbuzz.cc:13:
src/hb-ot-cff1-table.cc:36:17: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
using namespace CFF;
                ^
In file included from src/harfbuzz.cc:14:
src/hb-ot-cff2-table.cc:35:17: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
using namespace CFF;
                ^
2 errors generated.